export const ADD_TODO = 'ADD_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'
export const CLEAR_ALL = 'CLEAR_ALL'
export const COMPLETE_TODO = 'COMPLETE_TODO'
export const FILTER_TODOS = 'FILTER_TODOS'
